### ISSUE TITLE
Ошибка при использовании определенных имен файлов шаблонов

### ISSUE THREAD

**Issue by fobdy** [KosyanMedia/temple#10]
Решил попробовать после конференции вашу разработку ;)
Значит, если я файл называю как-то отлично от правил наименования js identifier, то все валится.

К примеру, файл `hello-world.temple`.

Генерится такой код:

```javascript
var templates_list = {hello-world: '...' }
```

Тут оно и валится, т.к. надо заэкранировать название `hello-world` в кавычки.

**Comment by fobdy** [comment]
Куку

**Comment by bskaplou** [comment]
Сори за небыстрый ответ, да на имена ограничения - все они должны быть валидными именами js. Зачиним!
